version: '3.9'

services:
  backend:
    build:
      context: https://github.com/lmmeqa/chorely-backend.git
      dockerfile: Dockerfile_demo
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/chorely
      - MUTE_DB_LOGS=${MUTE_DB_LOGS:-}
      - MUTE_API_LOGS=${MUTE_API_LOGS:-}
      - MUTE_ERROR_LOGS=${MUTE_ERROR_LOGS:-}
      - SHOW_API_PAYLOADS=${SHOW_API_PAYLOADS:-}
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chorely
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
